// Dados demo para quando Supabase não está conectado
export const DEMO_KPIS = {
  grupos_ativos: 3,
  total_membros: 1847,
  ofertas_hoje: 42,
  enviadas_hoje: 38,
  comissoes_mes: 1285.50,
  vendas_mes: 67,
  cliques_hoje: 234,
};

export const DEMO_GRUPOS = [
  {
    id: '1',
    nicho: 'tenis',
    numero_sequencial: 1,
    nome_grupo: 'Tênis Ofertas | 532',
    qtd_membros: 532,
    capacidade_maxima: 950,
    status: 'ativo',
    total_ofertas_enviadas: 1847,
    ofertas_hoje: 14,
    ultimo_envio_em: new Date().toISOString(),
    criado_em: '2026-06-15T10:00:00Z',
  },
  {
    id: '2',
    nicho: 'tenis',
    numero_sequencial: 2,
    nome_grupo: 'Tênis Ofertas | 2',
    qtd_membros: 890,
    capacidade_maxima: 950,
    status: 'ativo',
    total_ofertas_enviadas: 923,
    ofertas_hoje: 12,
    ultimo_envio_em: new Date().toISOString(),
    criado_em: '2026-07-01T10:00:00Z',
  },
  {
    id: '3',
    nicho: 'tenis',
    numero_sequencial: 3,
    nome_grupo: 'Tênis Ofertas | 3',
    qtd_membros: 425,
    capacidade_maxima: 950,
    status: 'ativo',
    total_ofertas_enviadas: 312,
    ofertas_hoje: 12,
    ultimo_envio_em: new Date().toISOString(),
    criado_em: '2026-07-20T10:00:00Z',
  },
];

export const DEMO_OFERTAS = [
  {
    id: '1',
    plataforma: 'shopee',
    categoria: 'tenis',
    titulo_original: 'Tênis Olympikus Valence 3',
    titulo_gerado: 'ESSE GOSTA DE IR RÁPIDO MESMO 🏃',
    preco_de: 349.99,
    preco_por: 177.00,
    desconto_pct: 49.4,
    cupom: 'FASHIONML',
    link_afiliado: 'https://meli.la/2LLL1z',
    imagem_url: null,
    status: 'enviada',
    fonte: 'api_afiliado',
    criado_em: new Date().toISOString(),
  },
  {
    id: '2',
    plataforma: 'mercado_livre',
    categoria: 'tenis',
    titulo_original: 'Kit com 3 Pares de Meias Antiderrapante Futebol',
    titulo_gerado: '7 CONTO CADA MEIA PRA RAPAZIADA DO FUT ⚽',
    preco_de: 49.90,
    preco_por: 21.00,
    desconto_pct: 57.9,
    cupom: 'MEIAPARAVOCE',
    link_afiliado: 'https://meli.la/2LLL1z',
    imagem_url: null,
    status: 'enviada',
    fonte: 'api_afiliado',
    criado_em: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: '3',
    plataforma: 'netshoes',
    categoria: 'tenis',
    titulo_original: 'Tênis Nike Revolution 7 Masculino',
    titulo_gerado: 'NIKE POR PREÇO DE CHINELO 🔥',
    preco_de: 399.99,
    preco_por: 199.99,
    desconto_pct: 50.0,
    cupom: 'AGORAVAI',
    link_afiliado: 'https://netshoes.com.br/p/xxx',
    imagem_url: null,
    status: 'aprovada',
    fonte: 'api_afiliado',
    criado_em: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: '4',
    plataforma: 'centauro',
    categoria: 'tenis',
    titulo_original: 'Tênis Adidas Runfalcon 4.0 Masculino',
    titulo_gerado: null,
    preco_de: 349.99,
    preco_por: 179.99,
    desconto_pct: 48.6,
    cupom: null,
    link_afiliado: 'https://centauro.com.br/p/xxx',
    imagem_url: null,
    status: 'pendente',
    fonte: 'api_afiliado',
    criado_em: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const DEMO_COMISSOES = [
  { id: '1', plataforma: 'shopee', valor_venda: 177.00, valor_comissao: 14.16, status: 'aprovada', registrado_em: new Date().toISOString() },
  { id: '2', plataforma: 'mercado_livre', valor_venda: 299.90, valor_comissao: 29.99, status: 'paga', registrado_em: new Date(Date.now() - 86400000).toISOString() },
  { id: '3', plataforma: 'netshoes', valor_venda: 199.99, valor_comissao: 12.00, status: 'pendente', registrado_em: new Date(Date.now() - 172800000).toISOString() },
  { id: '4', plataforma: 'shopee', valor_venda: 89.90, valor_comissao: 7.19, status: 'aprovada', registrado_em: new Date(Date.now() - 259200000).toISOString() },
  { id: '5', plataforma: 'centauro', valor_venda: 449.90, valor_comissao: 22.50, status: 'paga', registrado_em: new Date(Date.now() - 345600000).toISOString() },
];

export const DEMO_ENVIOS_FILA = [
  { id: '1', oferta_titulo: 'Tênis Puma Future Z', grupo_nome: 'Tênis Ofertas | 532', agendado_para: new Date(Date.now() + 300000).toISOString(), status: 'agendado' },
  { id: '2', oferta_titulo: 'Tênis Mizuno Wave', grupo_nome: 'Tênis Ofertas | 2', agendado_para: new Date(Date.now() + 900000).toISOString(), status: 'agendado' },
  { id: '3', oferta_titulo: 'Chuteira Nike Phantom', grupo_nome: 'Tênis Ofertas | 3', agendado_para: new Date(Date.now() + 1500000).toISOString(), status: 'agendado' },
];
